#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#batchexecutor;
pub mod r#context;
pub mod r#datatypes;
pub mod r#deploybatchexecutor;
pub mod r#erc20;
pub mod r#ierc20;
pub mod r#helperconfig;
pub mod r#iaavev2pool;
pub mod r#iaavev3pool;
pub mod r#ipool;
pub mod r#iaerodromepool;
pub mod r#iaerodromerouter;
pub mod r#irouter;
pub mod r#ierc165;
pub mod r#ierc20metadata;
pub mod r#ierc721;
pub mod r#ierc721enumerable;
pub mod r#ierc721metadata;
pub mod r#ierc721tokenreceiver;
pub mod r#iexecutor;
pub mod r#imorpho;
pub mod r#imorphobase;
pub mod r#imorphostatictyping;
pub mod r#ipooladdressesprovider;
pub mod r#iuniswapv2router;
pub mod r#iuniswapv3pool;
pub mod r#iuniswapv3poolactions;
pub mod r#iuniswapv3poolderivedstate;
pub mod r#iuniswapv3poolevents;
pub mod r#iuniswapv3poolimmutables;
pub mod r#iuniswapv3poolowneractions;
pub mod r#iuniswapv3poolstate;
pub mod r#iuniswapv3router;
pub mod r#iweth;
pub mod r#mockerc20;
pub mod r#mockerc721;
pub mod r#safetransferlib;
pub mod r#weth;
pub mod r#ierc1155errors;
pub mod r#ierc20errors;
pub mod r#ierc721errors;
