#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#context;
pub mod r#deploytxsimulator;
pub mod r#erc20;
pub mod r#ierc20;
pub mod r#helperconfig;
pub mod r#iaavev2pool;
pub mod r#iaavev3pool;
pub mod r#iaerodromepool;
pub mod r#iaerodromerouter;
pub mod r#irouter;
pub mod r#icurvepool;
pub mod r#icurvepoolv2;
pub mod r#ierc165;
pub mod r#ierc20metadata;
pub mod r#ierc721;
pub mod r#ierc721enumerable;
pub mod r#ierc721metadata;
pub mod r#ierc721tokenreceiver;
pub mod r#iexecutor;
pub mod r#iuniswapv2pool;
pub mod r#iuniswapv2router;
pub mod r#iuniswapv3quoterv2;
pub mod r#iuniswapv3quoterv2lib;
pub mod r#iuniswapv3router;
pub mod r#iweth;
pub mod r#mockerc20;
pub mod r#mockerc721;
pub mod r#safemath;
pub mod r#safetransferlib;
pub mod r#txsimulator;
pub mod r#uniswapv2library;
pub mod r#weth;
pub mod r#ierc1155errors;
pub mod r#ierc20errors;
pub mod r#ierc721errors;
